- name: Deply Dockerized Application
  hosts: 10.10.10.1
  become: true

  tasks:
    - name: Ensure Docker and Docker compose are installed
      apt:
        name:
          - docker-ce
          - docker-compose
        state: present
        update_cache: yes
      become: true

    - name: Pull Docker image from Docker Hub (if needed)
      docker_image:
        name: image_name:latest
        source: pull

    - name: Stop amd remove any existing Docker container
      docker_container:
        name: container_name
        state: absent
      ignore_errors: yes

    - name: Deploy Docker container
      docker_container:
        name: container_name
        image: image_name:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"

    - name: Wait for application to be reachable
      wait_for:
        host: localhost
        port: 8080
        state: started
      delegate_to: localhost

  handlers:
    - name: Restart Docker container
      docker_container:
        name: container_name
        stateL restarted
